runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /img
  static_dir: img

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /bootstrap
  static_dir: bootstrap


- url: /.*
  script: hoop_picks.app


- url: /cron/.*
  script: hoop_picks.app
  login: admin

- url: /admin/.*
  script: IGNORED
  login: admin
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
