runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /css
  static_dir: public/css
- url: /js
  static_dir: public/js
- url: /img
  static_dir: img
- url: /src
  static_dir: src

- url: /goatfavicon\.ico
  static_files: goatfavicon.ico
  upload: goatfavicon\.ico

- url: /bootstrap
  static_dir: bootstrap


- url: /.*
  script: main.app


- url: /cron/.*
  script: main.app
  login: admin

- url: /admin/.*
  script: IGNORED
  login: admin
# [END handlers]

# [START libraries]
libraries:
- name: ssl
  version: 2.7
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
